packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'
overrides:
  postcss: ^8.5.15
