packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'
overrides:
  postcss: ^8.5.15
